// Given two strings s and t which consist of only lowercase letters.
//
// String t is generated by random shuffling string s and then add one more letter at a random position.
//
// Find the letter that was added in t.
//
// Example:
//
// Input:
// s = "abcd"
// t = "abcde"
//
// Output:
// e
//
// Explanation:
// 'e' is the letter that was added.

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    if(!s) return t

    let letters = {}

    for(let i = 0; i < s.length; i++) {
        if(letters[s[i]]) {
            letters[s[i]] += 1
        } else {
            letters[s[i]] = 1
        }
    }

    for(let j = 0; j < t.length; j++) {
        if(letters.hasOwnProperty(t[j])) {
            letters[t[j]] -= 1
        } else {
            return t[j]
        }

        if(letters[t[j]] < 0) return t[j]
    }
};
